# Generated by Django 5.1.2 on 2024-10-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="achievements",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="degrees_and_institutions",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="hobbies_and_interests",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="institutions_taught_at",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="languages_spoken",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="location",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="professional_development",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="relevant_courses",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="social_media_links",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="soft_skills",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="student_reviews",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="subject_matter_expertise",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="subjects_and_levels_taught",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="teaching_philosophy",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="technical_skills",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="total_years_of_experience",
        ),
        migrations.AddField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(blank=True, to="student_app.subject"),
        ),
    ]
