# Generated by Django 5.1 on 2024-10-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_app", "0002_remove_teacher_achievements_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.TextField(max_length=255)),
                ("teacher_name", models.TextField(max_length=255)),
                ("capacity", models.IntegerField()),
            ],
        ),
    ]
