# Generated by Django 5.1.2 on 2024-10-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_app", "0004_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentleaverequest",
            name="status",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="teacherleaverequest",
            name="status",
            field=models.BooleanField(),
        ),
    ]
