# Generated by Django 5.1.2 on 2024-10-23 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_app", "0006_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
